Add nginx config file to api Dockerfile volume
AcompanhaLegis/acompanha-legis-api pull request #3
Opened 2020-09-22 23:35 UTC by leandro2r

2020-09-23 21:22 UTC, kimuraz requested changes
Nice work :medal_military: 

Let me know your though about the comments :+1:

2020-09-23 21:22 UTC, kimuraz commented on docker-compose.yml
>        - ./.env.example
I guess here it's the same 😬

2020-09-23 21:22 UTC, kimuraz commented on docker-compose.dev.yml
> +      - ./.env.example
Shouldn't we use the `.env` file? There are some instructions on README.md to copy `.env.example` to `.env` to start using it, also the `.example` may suggest it wasn't supposed to be used, what do you think?

2020-09-24 12:18 UTC, leandro2r commented on docker-compose.dev.yml
> +      - ./.env.example
My fault, I hadn't seen these instructions on the README.

2020-09-24 12:18 UTC, leandro2r commented on docker-compose.yml
>        - ./.env.example
Agreed

2020-09-30 18:21 UTC, kimuraz approved these changes
:1st_place_medal:

2020-09-30 18:21 UTC, merged